language: go
go:
- 1.11.5

# dependencies for kit are not vendored and should always build with the latest version.
install:
  - go get github.com/golang/protobuf/proto
  - go get github.com/golang/groupcache

script:
  - make -C cvendor/libmseed
  - make -C cvendor/libslink
  - test -z "$(gofmt -s -l `find . -name "*.go" | egrep -v vendor` | tee /dev/stderr)"
  - go vet -cgocall=false ./...
  - go test -v ./...
